"""Build source-linked slide content from the retained research snapshot."""
from pathlib import Path
import json
import pandas as pd
from supervisor_formula_legends import LEGENDS
from supervisor_dataset_slides import append_dataset_slides
from supervisor_task_sources import attach_task_sources

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'tmp/supervisor_deck'
R=ROOT/'results/joint_receiver_revision'
metrics=pd.read_csv(R/'response_metrics.csv')
global_data=pd.read_csv(R/'global_comparison.csv')
slides=[]
BASE='Selected bands, standard atmosphere, 45°, matched reference, 23 dBm and 6 dB noise figure'
CURRENT='docs/51_joint_design_time_calibration_results.md'
GUIDE='docs/50_species_methods_and_percentage_guide.md'
AUDIT='docs/49_completion_audit_and_fixes.md'
PAPER='paper/current_study.tex'

def add(title,body=None,formula=None,explain=None,result=None,limit=None,table=None,widths=None,chart=None,subtitle=None,notes='',sources=None,kind='standard'):
    slides.append(dict(title=title,body=body or [],formula=formula,explain=explain,result=result,limit=limit,table=table,widths=widths,chart=chart,subtitle=subtitle,notes=notes,sources=sources or [CURRENT,GUIDE],kind=kind))

def row(target,t=20,sigma=.0001,control='low',c=1.,plan='selected',profile='standard'):
    a=metrics[(metrics.target==target)&(metrics.total_s==t)&(metrics.residual_std_db==sigma)&(metrics.control==control)&(metrics.plan==plan)&(metrics.profile==profile)]
    if control=='low':a=a[a.concentration_ug_m3==c]
    assert len(a)==1
    return a.iloc[0]

add('Sub-THz atmospheric sensing',body=['What worked, how we achieved it, and what remains unresolved','Guillem Moreno Garcia\nUniversitat Politècnica de Catalunya\nSupervisor research review · 27 September 2026'],kind='cover',notes='This review describes the research snapshot at commit 461a3ba. Sensing performance remains conditional simulation. The original proposal contains eleven numbered subtasks.',sources=[AUDIT,'I2R_proposal_THz_ISAC (1).pdf'])
add('Problem statement',body=['Can a satellite communication downlink also detect gas and particle concentration changes using the same transmitted signal?','The proposal covers 60–400 GHz. Gas rotational lines provide spectral structure. Small particles produce a much smoother extinction signature.','The intended outcome combines useful recall, defensible concentration limits and an acceptable communication cost.'],formula='Observation = pollutant attenuation + atmospheric background + instrument error + noise',explain='The practical question is whether pollutant information survives the other unknowns.',limit='A correct forward model alone does not establish a useful environmental sensor.',sources=['I2R_proposal_THz_ISAC (1).pdf',AUDIT])
add('What we have achieved',table=[['Achievement','Evidence','Boundary'],['Physical model','Layered gas, particle, ray and thermal calculations','Conditional atmospheric and material assumptions'],['VOC detection','CH₃CN recall 97.67% at 1 µg/m³','20 s total and assumed 0.0001 dB residual'],['Engineering comparison','Sequential bands and moving coded-frame controls','RF specifications remain unmeasured'],['Failure diagnosis','PM information, gain drift and communication cost quantified','Useful joint VOC/PM retrieval remains open']],widths=[260,430,446],subtitle='A completed computational assessment with a conditional VOC improvement',limit='The 97.67% result uses the selected five-gas design with matched reference weather, 45° elevation, 23 dBm and 6 dB noise figure.',notes=BASE+'. 10,000 positive trials and 10,000 null trials. Exact recall interval 97.355–97.957%. Family false alarms 0.79%. All five gases and two PM masses remain unknown.',sources=[CURRENT,AUDIT])
add('The original eleven tasks',table=[['Task','Original requirement','Current outcome'],['1.1','Stratified atmosphere','Implemented with standard and measured weather'],['1.2','Spectroscopic inputs','Five target VOCs and traceable catalog gaps'],['1.3','Line shape and slant integration','Voigt profiles and refracted spherical paths'],['1.4','Particle extinction baseline','Rayleigh and Mie models, negative retrieval finding'],['2.1','Link and radio parameters','Explicit sequential receiver and resource budget'],['2.2','Simulated CSI','AWGN and bounded moving waveform controls'],['3.1','Spectral separation','Joint inference with nuisance projection'],['3.2','Concentration inversion','Payload moments and signed statistical estimates'],['4.1','Variance lower bounds','Nuisance-aware likelihood and Fisher bounds'],['4.2','Sensitivity','Common VOC/PM multivariable comparisons'],['4.3','Detection floors and standards','Conditional limits, no positive compliance claim']],widths=[110,395,631],notes='Each numbered task receives method and result slides. Task 3.2 lists statistical, optimization and ML methods as alternatives. A neural network is not a mandatory missing requirement.',sources=['I2R_proposal_THz_ISAC (1).pdf',AUDIT],kind='dense')
add('Evidence and operating conditions',table=[['Evidence','What it supports','What it cannot establish'],['HITRAN / ITU models','External physical parameters','Measured atmospheric radio performance'],['NOAA weather soundings','Actual weather profiles at selected times','Paired VOC/PM concentration truth'],['Monte Carlo responses','Conditional recall and concentration errors','Field recall under unknown model error'],['Raw coded OFDM frames','Bounded modem and synchronization checks','Full mission or continuous trajectory validation'],['Public water / calcite data','Limited independent physical checks','Calibrated joint VOC and PM retrieval']],widths=[265,400,471],limit='Every favorable result needs its time, calibration, concentration and receiver assumptions.',notes='Default current comparison: '+BASE+'. Calibration standard deviation denotes an additional differential spectral residual after reference subtraction. Zero residual is ideal. Nonzero residuals are also unmeasured assumptions.',sources=[PAPER,GUIDE])

add('Task 1.1 · Stratified atmosphere',body=['Implemented ITU-R P.835 reference layers through 100 km and NOAA IGRA measured weather profiles.','Interpolated temperature and log pressure / water vapor across height. Explicitly modeled the continuation above each sounding.'],formula='nₛ(z) = cₛ,₀ Nₐ / Mₛ · exp(−z/Hₛ)\nP(z), T(z), water(z) determine the local spectrum',explain='nₛ is molecular number density. Use consistent mass units for cₛ,₀ and molar mass Mₛ. Hₛ is an assumed concentration scale height.',result='The channel responds to vertical weather variation instead of using one homogeneous slab.',limit='The assumed pollutant profile does not become measured truth because the weather profile is measured.',sources=[PAPER,GUIDE,'src/thz_isac/atmosphere.py'])
add('Task 1.1 · Results and profile uncertainty',table=[['Component','Implemented result','Remaining uncertainty'],['Weather archive','103,322 levels from 521 soundings','Only selected dates enter sensing comparisons'],['Seasonal cases','January, April, July and September examples','Four profiles do not describe a population'],['Measured profile tops','28.8–37.0 km above the station','Upper continuation follows a model'],['Gas / PM scale height','1,500 m / 1,000 m','Unknown real pollutant distributions']],widths=[275,440,421],formula='c(z) = c₀ exp(−z/H)  ⇒  retrieved c₀ depends on H',explain='The reported concentration is a surface-equivalent enhancement under the chosen profile.',limit='Absolute ground concentration still requires baseline abundance and a validated column-to-surface mapping.',notes='The newest exact receiver comparison uses standard atmosphere and the existing January sounding. Older broader sensitivity studies include the other months. Do not imply that all four profiles enter the newest 288-condition grid.',sources=[PAPER,GUIDE])
add('Task 1.2 · Spectroscopic extraction',body=['Acquired line positions, strengths, pressure shifts, air broadening and temperature exponents from HITRAN.','Used isotope-specific masses and partition functions. Preserved line-source hashes and failed acquisition requests.'],formula='σₛ(ν,z) = Σℓ Sℓ(T(z)) Vℓ(ν − νℓ − δℓP(z))',explain='σₛ is molecular cross section. Sℓ is line strength and Vℓ is the normalized Voigt profile for local temperature and pressure.',result='The joint receiver now includes five organic gas targets and four interfering gases.',limit='HITRAN strengths already include natural isotope abundance. Applying it twice would understate absorption.',notes='Voigt Doppler width uses isotope mass. Reported mass concentration uses the natural-mixture molar mass. HCOOH rotational intensities involve dipole-based calculations and do not remove spectroscopy uncertainty.',sources=[GUIDE,'https://hitran.org/media/refs/HITRAN-2024.pdf','https://www.hitran.org/docs/molec-meta/'])
add('Task 1.2 · Every target gas and catalog gap',table=[['Target','Chemical identity','Current sensing result'],['H₂CO','Formaldehyde, an aldehyde','Weak recall at 1 µg/m³'],['CH₃OH','Methanol, an alcohol','Weak recall at 1 µg/m³'],['CH₃CN','Acetonitrile, a nitrile','Strongest low-concentration candidate'],['CH₃Cl','Chloromethane, a halogenated gas','Improves at higher concentration'],['HCOOH','Formic acid, a carboxylic acid','Largest current 95% concentration limit']],widths=[175,455,506],subtitle='CO, O₃, SO₂ and NO₂ enter as interferents. H₂O and O₂ enter the atmospheric background.',limit='CH₃Br, C₂H₄, CH₃F and CH₃I lack suitable lines in the acquired HITRAN window. This does not prove zero absorption.',notes='VOC is the project shorthand for these selected organic gases, not a universal regulatory classification. The retained coverage review uses HITRAN2024 Table 1, page 7. Additional candidates need usable microwave strengths and pressure broadening before quantitative inference.',sources=[GUIDE,'results/joint_receiver_revision/missing_spectroscopy_review.json'])
add('Task 1.3 · Voigt profiles and slant propagation',body=['Combined Doppler and pressure broadening at each atmospheric layer.','Integrated along a spherical refracted ray connecting receiver and satellite. Used atmospheric interfaces and numerical quadrature.'],formula='Aₛ(ν) = (10 / ln 10) ∫ray nₛ(z) σₛ(ν,z) ds\nPout / Pin = 10^(−A/10)       b = n(r) r sin ζ',explain='A is power attenuation in dB. b is the spherical ray invariant and ζ is the local zenith angle.',result='Elevation changes both the optical path and the received SNR.',limit='A secant factor applied after vertical integration cannot represent all refracted path effects.',sources=[PAPER,GUIDE])
add('Task 1.3 · Numerical convergence and thermal correction',table=[['Quantity','Relative RMS difference','Interpretation'],['Gas integration','0.00381%','Below the declared 0.1% numerical tolerance'],['PM integration','0.0225%','Below the declared tolerance'],['Atmospheric background','0.00200%','Below the declared tolerance'],['Thermal calculation, initial','0.11596%','Failed and triggered refinement'],['Thermal calculation, refined','0.00319%','Passed without relaxing the tolerance']],widths=[390,235,511],formula='Tsky = Σᵢ Jν(Tᵢ)(1 − e^(−τᵢ)) e^(−Σⱼ<ᵢ τⱼ) + transmitted space term',explain='Layer emission contributes receiver noise as well as attenuation.',limit='These are numerical checks on the tested grid. They do not measure atmospheric model error.',notes='An independent recursive transfer reproduced the refined brightness. Earlier seasonal weather calculations use order two and only September has its own separate order check. Current selected-tone calculations inherit declared quadrature. Do not claim convergence for every possible weather realization.',sources=[PAPER,'docs/45_payload_bounds_results.md'])
add('Task 1.4 · Rayleigh and Mie particle models',body=['Integrated spherical Mie extinction over truncated lognormal particle size distributions and normalized it by dry mass.','Converted aerodynamic size cuts to physical particle dimensions using the assumed density and shape model.'],formula='κext = ∫ Cext(r) p(r) dr / ∫ (4πρr³/3) p(r) dr\nRayleigh: κabs ≈ 3k Im(q)/ρ     κsca ≈ 2k⁴r³|q|²/ρ',explain='q = (m² − 1)/(m² + 2). k is wave number, m complex refractive index, ρ density and r sphere radius.',result='Rayleigh and full Mie agree closely in this particle-size and frequency regime.',limit='Material refractive index, shape, composition and humidity response remain assumptions.',sources=[GUIDE,PAPER])
add('Task 1.4 · PM definitions and the negative result',table=[['Output','Mass represented','Current result'],['PM1','Below 1 µm aerodynamic diameter','Exploratory extra split fails numerical separation'],['PM2.5','Fine mass below 2.5 µm','No useful mass retrieval in the tested grid'],['Coarse PM','Disjoint 2.5–10 µm mass','Nearly collinear with the fine-mode signature'],['PM10','Fine plus coarse mass','Includes their covariance, no valid 95% limit']],widths=[185,435,516],formula='Var(PM10) = Var(fine) + Var(coarse) + 2 Cov(fine, coarse)',explain='The fine model truncates below 0.03 µm. PM10 includes PM2.5, so they are not disjoint particle populations.',limit='A gain slope removes much of smooth Rayleigh absorption. Shared scattering shapes leave extremely weak size information.',notes='Fine assumptions: density 1500 kg/m³, median physical size 0.5 µm, geometric spread 1.7, refractive index 1.5 + 0.01i. Coarse: 1800 kg/m³, 4 µm, 1.6, 1.53 + 0.01i. Rayleigh/Mie RMS differences are 0.00086% fine and 0.0201% coarse in the earlier physical check. Three-bin scaled inverse identity error is approximately 0.508 and fails the gate.',sources=[GUIDE,'docs/48_expanded_voc_pm_and_20s_calibration.md'])
add('Task 2.1 · Link budget and sequential receiver',body=['Specified a 550 km downlink, 23 dBm active transmit power, 0.50 / 0.30 m apertures and a nominal 6 dB noise figure.','Replaced the ideal simultaneous broad reference with one RF chain hopping across sixteen 16 MHz blocks within 220–330 GHz.'],formula='Pr(ν) = Pt(ν) Gt(ν) Gr(ν) [λ/(4πR)]² 10^(−A(ν)/10) / Limpl\nSNR(ν) = Pr(ν) / {kB[Tsky(ν) + T₀(F − 1)]}',explain='R is range, F the linear noise factor and Limpl the linear implementation loss. Receiver noise figure enters once.',result='Each block has sixteen 1 MHz tones. CP, pilots, full frames, reference time and retuning all consume the time budget.',limit='23 dBm across the selected bands and 6 dB receiver noise are unverified RF requirements.',sources=[GUIDE,'docs/47_receiver_design_and_calibration.md'])
trade=json.loads((R/'communication_tradeoff.json').read_text(encoding='utf-8'))
add('Task 2.1 · Resources and communication cost',table=[['Quantity','Current result'],['Total reference + sample time','20 s, split equally'],['Actual frame transmission / retuning','19.72 s / 0.032 s'],['Instantaneous bandwidth / RF chains','16 MHz / one'],['Selected schedule Gaussian rate',f"{trade['candidate_gaussian_rate_bps']/1e6:.2f} Mbit/s"],['Best tested fixed block Gaussian rate',f"{trade['best_fixed_block_among_tested']['gaussian_fixed_rate_bps']/1e6:.2f} Mbit/s"],['Rate loss against that fixed block',f"{trade['gaussian_rate_loss_vs_best_tested_fixed_pct']:.2f}%"]],widths=[620,516],formula='Rate = time-weighted Σk Δf log₂(1 + SNRk)',explain='The comparison uses equal instantaneous bandwidth, power and CP/pilot overhead. Both reference and sample carry payload.',limit='Zero architecture cost is not established. Gaussian rate is different from coded QPSK throughput.',notes='Best fixed block among tested candidates is centered at 224 GHz. This is not a global optimum over every possible communications design. The older 1.382% number isolates schedule counts and must not replace the full 14.64% comparison.',sources=['results/joint_receiver_revision/communication_tradeoff.json',CURRENT])
add('Task 2.2 · CSI and raw waveform simulation',body=['Generated complex line-of-sight observations with frequency-dependent attenuation and additive complex Gaussian noise.','Added raw IFFT/CP frames, timing acquisition, Doppler correction, pilot tracking and coded packet checks.'],formula='yk = hk xk + wk       wk ~ CN(0,Vk)\nx[n] = IFFT{Xk}       hk contains path gain, phase and absorption',explain='Separate raw frames test modem behavior. Large recall experiments draw joint sample moments and apply nonlinear inversion.',result='The simulation connects physical channel attenuation to a bounded moving receiver.',limit='The large recall study does not generate every raw waveform sample for every Monte Carlo trial.',sources=[GUIDE,'results/joint_receiver_revision/scope_boundaries.json'])
frames=pd.read_csv(R/'selected_raw_frames.csv')
add('Task 2.2 · What the waveform controls establish',table=[['Control','Retained result','Boundary'],['Selected-frequency coverage',f'{len(frames)} fresh raw frames','One frequency spot check per selected block'],['Timing acquisition',f'{frames.timing_correct.sum()} / {len(frames)} correct','Bounded integer timing model'],['Passive sensing','Identical decoded outputs in every case','Comparison uses the same scheduled modem'],['Coded information errors',str(int(frames.information_bit_errors.sum())),'Finite controlled simulation'],['Full mission dynamics','Still open','Fractional timing, clock drift and time dilation']],widths=[320,355,461],formula='fD ≈ (vr / c) fc',explain='Narrowband Doppler correction addresses carrier shift. Wideband time scaling requires additional receiver modeling.',limit='Oscillator noise, pointing, multipath and realistic reference availability remain open.',notes='These spot checks support bounded communication behavior, not a measured field recall or a continuous complete orbital pass. Selected_raw_frames.csv retains packet counts and residual CFO.',sources=['results/joint_receiver_revision/selected_raw_frames.csv','results/joint_receiver_revision/scope_boundaries.json'])
add('Task 3.1 · Joint spectral isolation',body=['Fitted all five gas signatures and two PM modes simultaneously.','Whitened the observation covariance and projected out gain offset/slope, atmospheric background and four interfering gases.'],formula='a = D c + N β + e       C = Cov(e)\nP = I − QN QNᵀ       ĉ = H a',explain='D contains target signatures. N contains nuisance signatures. QN spans the whitened nuisance space. An SVD constructs H.',result='Numerical gates check scaled H D ≈ I and nuisance rejection H N ≈ 0.',limit='No algorithm can separate an arbitrary gain error that occupies the same spectral direction as the pollutant.',sources=[GUIDE,'scripts/joint_receiver_support.py'])
old=row('CH3CN',plan='uniform').recall_pct
new=row('CH3CN').recall_pct
add('Task 3.1 · Frequency selection improves five-gas inference',body=['A deterministic coordinate-exchange screen selected sixteen blocks using the standard 45° design case.','The selection optimized the worst relative gas uncertainty while retaining PM and nuisance parameters. Exact tone spectra followed the coarse screen.'],table=[['CH₃CN at 1 µg/m³','Uniform bands','Selected bands'],['Simulated recall',f'{old:.2f}%',f'{new:.2f}%'],['Total acquisition time','20 s','20 s'],['Assumed residual standard deviation','0.0001 dB','0.0001 dB']],widths=[600,268,268],result='All five exact VOC information limits improve relative to the uniform design.',limit='January weather and response draws did not choose bands. Global optimality and unknown-weather robustness remain unproved.',notes=BASE+'. The fresh uniform control is 57.40%. The historical 56.63% value belongs to an earlier independent simulation. The selected result is a conditional improvement at equal resources.',sources=[CURRENT,'results/joint_receiver_revision/selection.json'])
add('Task 3.2 · Payload moments estimate signal and noise',body=['Used the existing constant-modulus QPSK payload instead of discarding most samples and retaining only 30 pilots per 10,000 symbols.','Applied the established M2M4 estimator with a finite-sample correction, then compared sample and reference powers.'],formula='M₂ = S + V       M₄ = S² + 4SV + 2V²\nS = √(2M₂² − M₄)       A = −10 log₁₀(Ssample / Sreference)',explain='S is received signal power. V is noise power. The moments separate signal and noise under the QPSK and Gaussian-noise model.',result='More existing symbols contribute information without adding sensing transmissions.',limit='Arbitrary QAM, nonlinear distortion or severe intercarrier interference invalidate these simple moments.',notes='M2M4 is established prior work. The contribution is its application, resource accounting and conditional evaluation here. Invalid inversions count as failures. Large experiments use the joint asymptotic distribution of second/fourth sample moments and nonlinear inversion. Raw QPSK controls independently test bounded cases.',sources=[GUIDE,'docs/42_payload_recall.md','https://arxiv.org/abs/2506.15998',PAPER])
gas=['H2CO','CH3OH','CH3CN','CH3Cl','HCOOH']
names=['Formaldehyde','Methanol','Acetonitrile','Chloromethane','Formic acid']
table=[['Gas','Recall at 1 µg/m³','Miss rate','95% limit µg/m³','Recall at that limit']]
for g,n in zip(gas,names):
    a=row(g);b=row(g,control='response95')
    table.append([n,f'{a.recall_pct:.2f}%',f'{a.miss_rate_pct:.2f}%',f'{b.concentration_ug_m3:.3f}',f'{b.recall_pct:.2f}%'])
add('Task 3.2 · Detection gains are species dependent',table=table,widths=[280,230,185,225,216],subtitle='20 s total, assumed 0.0001 dB residual, selected bands and standard atmosphere at 45°',result='Acetonitrile reaches 97.67% recall at 1 µg/m³. Other gases require higher concentrations.',limit='These are simulated detection frequencies, not measured field performance or concentration accuracy.',notes=BASE+'. Each positive and null class has 10,000 trials. Exact CH3CN interval 97.355–97.957%. Family false alarms 0.79%. At nominal 95% detection points relative concentration RMSE is about 21%, not 5%.',sources=[CURRENT,'results/joint_receiver_revision/response_metrics.csv'])
add('Task 4.1 · Lower bounds with nuisance parameters',body=['Derived full QPSK and magnitude likelihood information with unknown signal power, noise power and finite reference uncertainty.','Profiled nuisance parameters before comparing the attainable concentration covariance with the estimator variance.'],formula='Jab = E[(∂ log p(y;θ)/∂θa)(∂ log p(y;θ)/∂θb)]\nJeff = Jcc − Jcη Jηη⁻¹ Jηc       Cov(ĉ) ⪰ Jeff⁻¹',explain='c denotes target concentration and η all nuisance parameters. The Schur complement accounts for their uncertainty.',result='The bound identifies when replacing the estimator offers little remaining gain.',limit='The bound is local and conditional on the likelihood, covariance and physical signatures.',sources=['docs/44_payload_information_derivation.md','docs/45_payload_bounds_results.md'])
add('Task 4.1 · M2M4 is already close to the bound',table=[['Gas','CRLB / M2M4 variance','Historical 95% limit µg/m³'],['Formaldehyde','95.89%','4.456'],['Methanol','97.61%','10.307'],['Acetonitrile','96.49%','1.023']],widths=[345,400,391],subtitle='Historical broad reference, three target gases, 20 s total and zero extra calibration residual',formula='Efficiency = variance lower bound / estimator variance',explain='Values near 100% leave little improvement available from estimator replacement in this control.',result='The next substantial improvement came from frequency information and design.',limit='These historical bounds use a different architecture and target family from the current five-gas receiver.',notes='Standard atmosphere at 45°, charged 10 s reference plus 10 s sample, unknown noise and joint spectral nuisance. The prior six-output family differs from the current eight-output family. Do not use this table to rank current and old designs as equal conditions.',sources=['docs/45_payload_bounds_results.md'])
add('Task 4.2 · Time and calibration jointly set uncertainty',body=['Recomputed the link, absorption, emission and target fit when weather, elevation, bands or receiver noise change.','The latest common grid contains every VOC, PM2.5, coarse PM and PM10 in every operating condition.'],formula='C(t,σcal) = diag[Vsample(t/2) + Vreference(t/2)] + σcal²K\nKij = exp(−|νi − νj| / 10 GHz)',explain='Thermal variance decreases with retained symbols. The additional calibration residual persists through the acquisition.',result='More time helps until persistent calibration error dominates.',limit='The 10 GHz correlation length and each calibration standard deviation remain unmeasured assumptions.',sources=[GUIDE,'results/joint_receiver_revision/global_comparison_protocol.json'])
series=[]
for sigma,color in [(0,'#176B87'),(.0001,'#D48426'),(.001,'#AC3B4A')]:
    series.append(dict(name=f'{sigma:g} dB',values=[row('CH3CN',t=t,sigma=sigma).recall_pct for t in [2,20,100]],color=color))
add('Task 4.2 · Longer time cannot remove calibration error',chart=dict(categories=['2 s','20 s','100 s'],series=series,ytitle='Simulated recall (%)'),subtitle='Acetonitrile at 1 µg/m³, selected bands, standard atmosphere at 45°',result='At 0.001 dB, recall is only 4.36% at 20 s and 5.05% at 100 s.',limit='Zero and nonzero residuals are sensitivity assumptions. No receiver stability measurement establishes them.',notes=BASE+'. Curves use separate finite Monte Carlo samples. The 100% observed values retain confidence intervals below perfect population recall. The covariance is persistent within each acquisition.',sources=[CURRENT,'results/joint_receiver_revision/response_metrics.csv'])
add('Task 4.2 · PM shares the full global comparison',table=[['Variable','Compared settings'],['Frequency plan','Uniform and selected sixteen-block schedules'],['Atmosphere','Standard and January sounding'],['Elevation','30°, 45°, 60°, 90°'],['Reference + sample time','2 s, 20 s, 100 s'],['Assumed calibration residual','0, 0.0001, 0.001 dB'],['Receiver noise figure','6 dB and 17 dB']],widths=[490,646],result='288 conditions × 8 outputs = 2,304 rows. Each output has 270 computed and 18 rejected conditions.',limit='No valid 95% response limit for PM2.5 or PM10 anywhere in this grid.',notes='Fixed 23 dBm transmit power, matched reference weather, 10 GHz residual correlation. All rejected cases are standard atmosphere, 30° elevation, 17 dB noise figure for both schedules and all times/calibrations. Their target separation fails the numerical gate. Failed rows remain present and do not receive fabricated zero recall.',sources=['results/joint_receiver_revision/global_comparison.csv','results/joint_receiver_revision/global_comparison_protocol.json'])
add('Task 4.3 · Detection limits and percentage definitions',body=['Fixed a 1% family false-alarm budget across eight outputs before observing outcomes.','Solved the concentration for nominal 95% power using positive-signal variance, then tested it with fresh simulated responses.'],formula='z = Φ⁻¹(1 − 0.01/8)       detect if ĉj > z snull\nc95 = z snull + 1.64485 spositive(c95)',explain='Positive absorption changes SNR and variance. The solution stays within at most 1 dB added absorption.',result='Reports include low recalls, missed detections, exact binomial intervals and concentration RMSE.',limit='95% detection power, a 95% confidence interval and 5% concentration error describe different quantities.',notes='Recall = TP/(TP+FN). False alarms = FP/(FP+TN). Relative RMSE = sqrt(mean((estimate−truth)^2))/truth. Precision and F1 use artificial 50% prevalence. A missing in-domain solution remains unavailable. The PM10 output participates in the family although it derives from two masses.',sources=[GUIDE,'scripts/evaluate_joint_receiver.py'])
table=[['Total s','Residual dB','H₂CO','CH₃OH','CH₃CN','CH₃Cl','HCOOH']]
for t in [2,20,100]:
    for sig in [0,.0001,.001]:table.append([str(t),f'{sig:g}']+[f'{row(g,t=t,sigma=sig,control="response95").concentration_ug_m3:.3f}' for g in gas])
add('Task 4.3 · Every 95% limit needs time and calibration',table=table,widths=[125,180,166,166,167,166,166],subtitle='Nominal 95% response concentration in µg/m³, selected bands, standard atmosphere at 45°',limit='PM2.5, coarse PM and PM10 have no valid 95% response limit in these nine conditions.',notes=BASE+'. Values solve positive-response variance and precede Monte Carlo evaluation. Actual simulated recalls near 95% remain as measured fractions in the response CSV. All calibration levels are assumed.',sources=[CURRENT,'results/joint_receiver_revision/response_metrics.csv'],kind='dense')
add('Task 4.3 · Environmental interpretation remains open',body=['Converted gas mass to surface-equivalent mole fraction using pressure, temperature and molar mass.','Observable: short slant-path enhancement relative to a reference. Ambient guidance has distinct location and averaging requirements.','PM reference masses are 15 and 45 µg/m³. These tests do not establish compliance.'],formula='ppm = cµg/m³ R T / (p Mg/mol)',explain='The numeric conversion assumes the displayed mass and molar-mass units. PM has mass units and no gas ppm conversion.',result='The study reports conditional floors and an explicit negative / unverified standards assessment.',limit='Unknown baseline abundance, vertical profiles, PM information and independent truth prevent a positive compliance claim.',notes='The prior standards review discusses WHO 2021 ambient PM guidelines and separate indoor formaldehyde guidance. These are different domains and time averages. This presentation does not interpret short radio enhancements as regulatory measurements.',sources=[GUIDE,'docs/45_payload_bounds_results.md','docs/41_measurement_protocol.md'])
add('Calibration is the critical engineering requirement',body=['Zero calibration error means zero additional differential residual after modeled corrections. Thermal noise and reference uncertainty still remain.','At 20 s, the local CH₃CN requirement for 95% power at 1 µg/m³ is approximately 0.000146 dB residual standard deviation under the nominal covariance.'],formula='|bi| ≤ ε  ⇒  Bj = ε ‖Hj‖₁\nProtected local requirement ≈ (z + 1.64485)sj + 2Bj',explain='A persistent signed bias can move both the null threshold and the positive response in the adverse direction.',result='Calibration requirements are now quantitative and retained with every result.',limit='A small random standard deviation does not guarantee resistance to arbitrary drift or unknown hop gains.',notes='The 0.000146 dB number is a local requirement, not a measured achieved accuracy. Independent hop-gain nuisance terms make the current separation unstable. Prior zero-calibration headline controls are retained separately in the permanent calibration note.',sources=['docs/46_critical_calibration_assumption.md','results/joint_receiver_revision/calibration_requirements.csv',GUIDE])
add('Failures that constrain the claimed achievement',table=[['Failure or stress','Finding','Implication'],['PM mass and extra size split','Negligible useful information / unstable inverse','A successful optimizer cannot repair missing information'],['Unknown relative hop gains','Target separation fails','Requires calibrated relative spectral response'],['Weather mismatch','Frozen standard operator acquires bias','Matched-weather success is insufficient'],['Unamplified RF converter','Fails usable-SNR gate','Nominal power requires a complete RF chain'],['Modulation / receiver mismatch','Simple payload moments may become invalid','Receiver assumptions need dedicated validation']],widths=[310,365,461],limit='The intended general atmospheric VOC/PM instrument remains an open research outcome.',notes='All listed failures remain in the current audit and retained stress outputs. The nominal 17 dB noise-figure grid also rejects standard atmosphere at 30° for both schedules. Successful runs do not conceal those cases.',sources=[AUDIT,'results/joint_receiver_revision/stress_sensitivity.csv'])
add('Remaining problems and evidence needed',table=[['Open problem','Evidence required to close it'],['RF hardware and calibration','Measured power, noise, settling, spectral covariance and drift at selected tones'],['PM mass / composition','Paired optical properties, humidity, particle size and independent mass truth'],['Weather and concentration profiles','Independent profiles, column information and reference abundance'],['Full receiver dynamics','Continuous time-scaled channel with fractional timing, oscillator and pointing errors'],['Independent validation','Separate calibration and test campaigns with paired radio / concentration data'],['Deployment and environmental use','Applicable averaging domain, spectrum coordination and realistic operational coverage']],widths=[380,756],notes='Complete remaining-work ledger: docs/49_completion_audit_and_fixes.md. Additional unresolved details include unequal dwell/global frequency optimization, spectroscopy uncertainty, real-time hardware latency, atmospheric horizontal variability and communication coding/adaptation baselines.',sources=[AUDIT,'docs/41_measurement_protocol.md'])
add('Proposed next experiments',table=[['Priority','Experiment','Decision it enables'],['1','Repeated blank / reference acquisitions at selected tones','Can the required differential stability be achieved?'],['2','Controlled gas path with independent concentration truth','Does the predicted VOC recall survive real model error?'],['3','PM cell with known mass, size and humidity','Does radio information separate mass from composition?'],['4','Full receiver and reference schedule under motion','Can the sensing result survive operational timing?']],widths=[110,550,476],result='Freeze calibration and model choices before evaluating an independent test campaign.',limit='Additional Monte Carlo trials improve numerical precision but cannot replace missing measurements.',notes='These are proposed next experiments. No campaign has been completed or funded by this presentation. Before hardware access, full warped-time simulation and an additional PM observable are the most useful computational follow-ups.',sources=[AUDIT,'docs/41_measurement_protocol.md'])
add('What we can report to the supervisor',body=['The original eleven modeling and simulation tasks now have implementations with traceable outputs.','Payload reuse and frequency selection improve conditional VOC detection. Acetonitrile reaches 97.67% recall at 1 µg/m³ with 20 s and assumed 0.0001 dB residual.','The analysis explains why PM remains weak and why more averaging cannot overcome persistent calibration error.','The next milestone is independent physical validation of the selected receiver and its concentration estimates.'],result='The main achievement is a reproducible feasibility assessment and a stronger, explicitly conditional VOC design.',limit='Useful joint PM retrieval, zero communication architecture cost and validated field performance remain unachieved.',notes=BASE+'. The current schedule loses 14.64% Gaussian rate against the best tested fixed block. Source snapshot 461a3ba retains 235 tests and 25,172 numerical checks. These verify implementation and consistency, not physical truth.',sources=[AUDIT,CURRENT])

table=[['Output','Reference µg/m³','Predicted recall range','Valid 95% limits / 270']]
for g in gas+['PM2.5','PMcoarse','PM10']:
    a=global_data[(global_data.target==g)&(global_data.status=='computed')]
    table.append([g,str(int(a.reference_concentration_ug_m3.iloc[0])),f'{a.predicted_recall_pct.min():.3f}–{a.predicted_recall_pct.max():.3f}%',str(a.response_lod95_ug_m3.notna().sum())])
add('Appendix · Global VOC and PM outcomes',table=table,widths=[240,240,380,276],subtitle='Envelopes over 270 valid operating conditions per output, with 18 additional rejected conditions',limit='Different reference concentrations and operating conditions prevent a direct same-condition species ranking.',notes='These are conditional predictions using positive-response variance, not Monte Carlo frequencies. Ranges are operating-condition envelopes, not confidence intervals. Full 288-condition axes appear on Task 4.2 slides. Power fixed at 23 dBm and reference weather matched.',sources=['results/joint_receiver_revision/global_comparison.csv'],kind='dense')
table=[['Total s','Residual dB','PM2.5 at 15 µg/m³','Coarse at 45 µg/m³','PM10 at 45 µg/m³']]
for t in [2,20,100]:
    for sig in [0,.0001,.001]:table.append([str(t),f'{sig:g}']+[f'{row(g,t=t,sigma=sig,c=c).recall_pct:.2f}%' for g,c in [('PM2.5',15),('PMcoarse',45),('PM10',45)]])
add('Appendix · Low PM recalls remain visible',table=table,widths=[125,180,277,277,277],subtitle='Simulated recall, selected bands, standard atmosphere at 45°, same joint five-gas fit',limit='These recalls are near the false-alarm scale. No cell establishes useful PM detection.',notes=BASE+'. PM10 positive injection uses fine/coarse fractions 49/90 and 41/90. Each class has 10,000 trials. Binomial variation explains small nonmonotonic differences near the null rate. PM10 variance includes the cross covariance.',sources=['results/joint_receiver_revision/response_metrics.csv'],kind='dense')
add('Appendix · Reproducible evidence map',table=[['Research material','Repository location'],['Original task definition','I2R_proposal_THz_ISAC (1).pdf'],['Current results and global comparison','docs/51_joint_design_time_calibration_results.md'],['Species, equations and metric definitions','docs/50_species_methods_and_percentage_guide.md'],['Complete open-issue ledger','docs/49_completion_audit_and_fixes.md'],['Critical calibration record','docs/46_critical_calibration_assumption.md'],['Data, trials, hashes and validation','results/joint_receiver_revision/'],['Current manuscript','output/pdf/thz_isac_pollutant_sensing_ieee.pdf']],widths=[410,726],subtitle='Research snapshot 461a3ba, 27 September 2026',notes='Repository: https://github.com/unworthyzeus/THz_ISAC_atmospheric_monitoring . The snapshot contains 235 passing tests and 25,172 numerical checks. These counts describe the computational research snapshot, not slide validation or independent physical evidence.',sources=[AUDIT,CURRENT])
add('Appendix · Physical and methodological sources',body=['HITRAN2024 and HAPI: line data, isotope handling and spectroscopic calculations.','ITU-R P.835 and P.676: reference atmosphere, oxygen/water absorption and atmospheric background.','NOAA IGRA: independent measured weather soundings.','Aliaga et al. (2024) and Yang et al. (2024): satellite differential absorption and gas/particle propagation context.','Xu, Fu and Kim (2025): using pilots and payloads for sensing. Established M2M4 literature supplies the signal/noise estimator.'],limit='Published models motivate and parameterize the study. They do not validate this receiver’s field performance.',notes='Sources:\nHITRAN2024: https://hitran.org/media/refs/HITRAN-2024.pdf\nHAPI: https://doi.org/10.1016/j.jqsrt.2016.03.005\nITU-R P.835-7: https://www.itu.int/rec/R-REC-P.835\nITU-R P.676-13: https://www.itu.int/rec/R-REC-P.676\nNOAA IGRA: https://www.ncei.noaa.gov/products/weather-balloon/integrated-global-radiosonde-archive\nAliaga et al.: https://doi.org/10.1109/JSTARS.2024.3480816\nYang et al.: https://doi.org/10.1109/OJCOMS.2024.3386759\nXu et al.: https://arxiv.org/abs/2506.15998\nM2M4: Gianmarco Romano, 2021, doi:10.3390/s21154950. See full references in current manuscript.',sources=[PAPER])

# Additional quantitative detail for the supervisor's technical review.
detail={
2:[['Frequency scope','60–400 GHz'],['Satellite altitude','550 km'],['Current outputs','5 VOCs + 3 PM'],['Family false alarms','1% budget']],
3:[['CH₃CN interval','97.36–97.96%'],['Family false alarms','0.79%'],['Band-selection gain','40.27 percentage points']],
4:[['Physical subtasks','4'],['Radio subtasks','2'],['Inversion subtasks','2'],['Performance subtasks','3']],
5:[['Trials per class','10,000'],['Current MC cases','12'],['Reference / sample','10 s / 10 s at 20 s'],['Measured field recall','Unavailable']],
6:[['Soundings parsed','521'],['Vertical levels','103,322'],['Gas scale height','1,500 m'],['PM scale height','1,000 m']],
7:[['Atmosphere top','100 km'],['Earlier weather cases','4 months'],['Newest exact grid','2 atmospheres']],
8:[['Current target gases','5'],['Interfering gases','4'],['Historical isotope tables','34'],['Historical 60–400 GHz lines','31,474']],
9:[['Formaldehyde 95% limit','7.846 µg/m³'],['Acetonitrile 95% limit','0.927 µg/m³'],['Formic acid 95% limit','30.550 µg/m³']],
10:[['Current elevations','30°, 45°, 60°, 90°'],['Numerical tolerance','0.1% RMS'],['Gas convergence','0.00381% RMS'],['Background convergence','0.00200% RMS']],
11:[['Lower-atmosphere refinement','100 m steps'],['Above 20 km','500 m steps'],['Separate September check','0.05304% RMS']],
12:[['Fine density','1,500 kg/m³'],['Coarse density','1,800 kg/m³'],['Fine index','1.5 + 0.01i'],['Coarse index','1.53 + 0.01i']],
13:[['Fine Rayleigh/Mie difference','0.00086% RMS'],['Coarse difference','0.0201% RMS'],['Three-bin inverse identity error','0.508, rejected']],
14:[['Power / noise figure','23 dBm / 6 dB'],['Implementation loss','5 dB'],['Instantaneous bandwidth','16 MHz'],['Settling per hop','1 ms']],
15:[['Selected center range','224–318.67 GHz'],['Pilot / frame symbols','30 / 10,000'],['CP / useful symbol','1 / 16']],
16:[['Blocks / tones per block','16 / 16'],['Frame length','10,000 symbols'],['Pilots per frame','30'],['Acquisition CFO stress','100 kHz']],
17:[['Information bits',f'{int(frames.information_bits.sum()):,}'],['Information bit errors',f'{int(frames.information_bit_errors.sum()):,}'],['Raw coded bit error rate',f'{100*frames.information_bit_errors.sum()/frames.information_bits.sum():.4f}%']],
18:[['Unknown target masses','7'],['Reported outputs','8 with PM10'],['Selected frequencies','256 tones'],['Scaled identity tolerance','10⁻⁵']],
19:[['Deterministic starts','3'],['Selected blocks','16'],['Improved exact gas limits','5 / 5']],
20:[['Pilot fraction per frame','0.3%'],['Payload fraction per frame','99.7%'],['Signal moments','Second and fourth'],['Modulation tested','QPSK']],
21:[['Positive / null trials','10,000 / 10,000'],['Family false alarms','0.79%'],['Relative RMSE at 95% points','Approximately 21%']],
22:[['Likelihoods','QPSK and magnitude'],['Unknown noise','Included'],['Finite reference','Included'],['Historical efficiency','95.89–97.61%']],
23:[['Historical output family','6'],['Acquisition split','10 s + 10 s'],['Calibration benchmark','Zero extra residual']],
24:[['Time grid','2 / 20 / 100 s'],['Residual grid','0 / 0.0001 / 0.001 dB'],['Noise-figure grid','6 / 17 dB'],['Calibration draws','Once per acquisition']],
25:[['20 s, 0 dB','99.28% recall'],['20 s, 0.0001 dB','97.67% recall'],['20 s, 0.001 dB','4.36% recall'],['100 s, 0.001 dB','5.05% recall']],
26:[['Common result rows','2,304'],['Rejected settings','Standard, 30°, NF 17 dB'],['PM predicted recall','Approximately 0.125%']],
27:[['One-sided target α','0.01 / 8 = 0.00125'],['Null threshold z','Approximately 3.023'],['Positive power target','95%'],['Absorption cap','1 dB']],
28:[['CH₃CN, 20 s / 0.0001 dB','0.927 µg/m³'],['CH₃CN, 100 s / 0.001 dB','3.468 µg/m³'],['Valid PM limits in nine cases','0']],
29:[['H₂CO current limit ppm',f"{row('H2CO',control='response95').surface_equivalent_ppm:.6f}"],['CH₃CN current limit ppm',f"{row('CH3CN',control='response95').surface_equivalent_ppm:.6f}"],['Limit conditions','20 s / 0.0001 dB'],['Ambient PM test masses','15 and 45 µg/m³']],
30:[['Required local σ at 20 s','About 0.000146 dB'],['Nominal random σ','0.0001 dB'],['Power change for 0.0001 dB','About 0.002303%'],['Field calibration records','None']],
31:[['Numerically rejected global cases','18 / 288'],['Useful PM limits','0 / 270 valid cases'],['Gaussian architecture rate loss','14.64%']],
32:[['Nominal RF target','23 dBm, NF 6 dB'],['Current calibration assumption','0.0001 dB'],['Current physical truth','No paired radio/VOC/PM test']],
33:[['Calibration acceptance question','σ ≤ about 0.000146 dB at 20 s?'],['Frozen test target','1 µg/m³ CH₃CN'],['Independent test measurements','Still required']],
34:[['Task implementations','11 / 11'],['Verified research checks','25,172'],['Conditional CH₃CN recall','97.67%'],['Validated field recall','Unavailable']],
35:[['Grid','2 plans × 2 weather × 4 elevations'],['Other axes','3 times × 3 residuals × 2 noise figures'],['Mass assumptions','1 / 15 / 45 µg/m³ (see table)']],
36:[['PM10 positive mixture','Fine 49/90, coarse 41/90'],['Null target threshold','0.125% theoretical marginal rate'],['Monte Carlo class size','10,000']],
37:[['Retained metric rows','480'],['Global rows','2,304'],['Passing research tests','235']],
38:[['Original tasks','11'],['Current source snapshot','461a3ba'],['Additional organic catalog gaps','4'],['Paired field validation','Open']]
}
for index,rows in detail.items():slides[index-1]['detail']=rows
slides[20]['table']=[['Gas','Recall at 1 (%)','Misses at 1 (%)','c95 µg/m³','Recall at c95 (%)','95% CI at c95 (%)','RMSE at c95 (%)']]
for g,n in zip(gas,names):
    a=row(g);b=row(g,control='response95')
    slides[20]['table'].append([n,f'{a.recall_pct:.2f}',f'{a.miss_rate_pct:.2f}',f'{b.concentration_ug_m3:.3f}',f'{b.recall_pct:.2f}',f'{b.recall_ci95_lower_pct:.2f}–{b.recall_ci95_upper_pct:.2f}',f'{b.relative_rmse_pct:.2f}'])
slides[20]['widths']=[230,175,175,180,205,260,231]
slides[16]['table'][4][1]=f"{int(frames.information_bit_errors.sum()):,} errors"
slides[16]['table'][4][2]=f"Across {int(frames.information_bits.sum()):,} information bits"

# Actual TeX source, compiled separately for vector equation assets.
latex={
2:r'\underbrace{\mathbf a}_{\text{observation}}=\underbrace{\mathbf D\mathbf c}_{\text{pollutants}}+\underbrace{\mathbf N\boldsymbol\beta}_{\text{background and instrument}}+\underbrace{\mathbf e}_{\text{noise}}',
6:r'\begin{aligned}n_s(z)&=\frac{c_{s,0}N_A}{M_s}\exp\!\left(-\frac{z}{H_s}\right),\\[4pt] \text{local spectrum}&\;\text{depends on }P(z),\;T(z),\;\rho_{\mathrm{H_2O}}(z)\end{aligned}',
7:r'c(z)=c_0\exp\!\left(-\frac{z}{H}\right)\qquad\Longrightarrow\qquad\widehat c_0\text{ depends on the assumed }H',
8:r'\sigma_s(\nu,z)=\sum_{\ell\in s}S_\ell\!\left(T(z)\right)\,V_\ell\!\left[\nu-\nu_\ell-\delta_\ell P(z);\,T(z),P(z)\right]',
10:r'\begin{aligned}A_s(\nu)&=\frac{10}{\ln 10}\int_{\mathrm{ray}}n_s(z)\,\sigma_s(\nu,z)\,\mathrm ds,\\[4pt]\frac{P_{\mathrm{out}}}{P_{\mathrm{in}}}&=10^{-A/10},\qquad b=n(r)\,r\sin\zeta\end{aligned}',
11:r'T_{\mathrm{sky}}=\sum_i J_\nu(T_i)\left(1-e^{-\tau_i}\right)e^{-\sum_{j<i}\tau_j}+J_\nu(T_{\mathrm{space}})e^{-\sum_i\tau_i}',
12:r'\begin{aligned}\kappa_{\mathrm{ext}}&=\frac{\int C_{\mathrm{ext}}(r)\,p(r)\,\mathrm dr}{\int \frac{4\pi}{3}\rho r^3p(r)\,\mathrm dr},\\[4pt]\kappa_{\mathrm{abs}}&\simeq\frac{3k\,\mathrm{Im}(q)}{\rho},\qquad\kappa_{\mathrm{sca}}\simeq\frac{2k^4r^3|q|^2}{\rho}\end{aligned}',
13:r'\mathrm{Var}(\mathrm{PM}_{10})=\mathrm{Var}(c_{\mathrm{fine}})+\mathrm{Var}(c_{\mathrm{coarse}})+2\,\mathrm{Cov}(c_{\mathrm{fine}},c_{\mathrm{coarse}})',
14:r'\begin{aligned}P_r(\nu)&=\frac{P_t(\nu)G_t(\nu)G_r(\nu)}{L_{\mathrm{impl}}}\left(\frac{\lambda}{4\pi R}\right)^2 10^{-A(\nu)/10},\\[4pt]\mathrm{SNR}(\nu)&=\frac{P_r(\nu)}{kB\left[T_{\mathrm{sky}}(\nu)+T_0(F-1)\right]}\end{aligned}',
15:r'\overline R=\sum_b\frac{t_b}{t_{\mathrm{total}}}\sum_{k\in b}\Delta f\log_2\!\left(1+\mathrm{SNR}_k\right)',
16:r'\begin{aligned}y_k&=h_kx_k+w_k,\qquad w_k\sim\mathcal{CN}(0,V_k),\\[4pt]x[n]&=\operatorname{IFFT}\{X_k\}\end{aligned}',
17:r'f_D\simeq\frac{v_r}{c}\,f_c',
18:r'\begin{aligned}\mathbf a&=\mathbf D\mathbf c+\mathbf N\boldsymbol\beta+\mathbf e,\qquad\mathbf C=\operatorname{Cov}(\mathbf e),\\[4pt]\mathbf P&=\mathbf I-\mathbf Q_N\mathbf Q_N^{\mathsf T},\qquad\widehat{\mathbf c}=\mathbf H\mathbf a\end{aligned}',
20:r'\begin{aligned}M_2&=S+V,\qquad M_4=S^2+4SV+2V^2,\\[4pt]S&=\sqrt{2M_2^2-M_4},\qquad A=-10\log_{10}\!\left(\frac{S_{\mathrm{sample}}}{S_{\mathrm{reference}}}\right)\end{aligned}',
22:r'\begin{aligned}J_{ab}&=\mathbb E\!\left[\frac{\partial\log p(y;\boldsymbol\theta)}{\partial\theta_a}\frac{\partial\log p(y;\boldsymbol\theta)}{\partial\theta_b}\right],\\[4pt]\mathbf J_{\mathrm{eff}}&=\mathbf J_{cc}-\mathbf J_{c\eta}\mathbf J_{\eta\eta}^{-1}\mathbf J_{\eta c},\qquad\operatorname{Cov}(\widehat{\mathbf c})\succeq\mathbf J_{\mathrm{eff}}^{-1}\end{aligned}',
23:r'\mathrm{Efficiency}=\frac{\text{variance lower bound}}{\text{estimator variance}}',
24:r'\begin{aligned}\mathbf C(t,\sigma_{\mathrm{cal}})&=\operatorname{diag}\!\left[\mathbf V_{\mathrm{sample}}(t/2)+\mathbf V_{\mathrm{reference}}(t/2)\right]+\sigma_{\mathrm{cal}}^2\mathbf K,\\[4pt]K_{ij}&=\exp\!\left(-\frac{|\nu_i-\nu_j|}{10\,\mathrm{GHz}}\right)\end{aligned}',
27:r'\begin{aligned}z&=\Phi^{-1}\!\left(1-\frac{0.01}{8}\right),\qquad\widehat c_j>z\,s_{\mathrm{null}},\\[4pt]c_{95}&=z\,s_{\mathrm{null}}+1.64485\,s_{\mathrm{positive}}(c_{95})\end{aligned}',
29:r'\chi_{\mathrm{ppm}}=\frac{c_{\mu\mathrm{g}/\mathrm m^3}\,R\,T}{p\,M_{\mathrm g/\mathrm{mol}}}',
30:r'\begin{aligned}|b_i|&\leq\varepsilon\quad\Longrightarrow\quad B_j=\varepsilon\,\lVert\mathbf H_j\rVert_1,\\[4pt]c_{95,\mathrm{protected}}&\simeq(z+1.64485)s_j+2B_j\end{aligned}'
}
for index,tex in latex.items():slides[index-1]['latex']=tex
add('Task 3.2 · Why payload reuse mattered',table=[['Historical control','Pilots','Payload M2M4','Reference assumption'],['CH₃CN, 1 µg/m³, 10 s','0.460% recall','99.955% recall','Exactly known reference'],['CH₃CN, 1 µg/m³, 20 s total','0.380% recall','93.800% recall','10 s independent reference + 10 s sample']],widths=[420,210,240,266],subtitle='Earlier ideal broad reference, three target gases and zero persistent calibration residual',result='Payload moments recover information that sparse pilot-only sensing discards.',limit='The ideal broad architecture and zero residual assumption prevent direct transfer to deployed hardware.',notes='Historical results in docs/42_payload_recall.md. This table compares methods within each original control. It is separate from the current five-gas hopping receiver and its eight-output false-alarm family. M2M4 itself is established prior work.',sources=['docs/42_payload_recall.md','docs/46_critical_calibration_assumption.md'])
historical=slides.pop();historical['detail']=[['Pilot samples per frame','30'],['Total symbols per frame','10,000'],['Old physical architecture','Ideal simultaneous broad bands']]
slides.insert(20,historical)
for index, slide in enumerate(slides, 1):
    if slide.get('latex'):
        slide['legend'] = LEGENDS[index]
assert set(LEGENDS) == {i for i, s in enumerate(slides, 1) if s.get('latex')}
append_dataset_slides(add, slides, ROOT)
attach_task_sources(slides)
slides[4]['subtitle'] = 'Each task explains its inputs on the method slide. Detailed dataset records remain on slides 40–44.'
OUT.mkdir(parents=True,exist_ok=True)
(OUT/'slides.json').write_text(json.dumps(slides,ensure_ascii=False,indent=2),encoding='utf-8')
md=['# Supervisor presentation notes','Research snapshot: 461a3ba. Each task has method and result slides.']
for i,s in enumerate(slides,1):
    md += [f'\n## Slide {i}: {s["title"]}',s.get('subtitle') or '',*s['body']]
    if s['formula']:md += ['\nEquation: '+s['formula'],'\n'+(s['explain'] or ''),'\nLaTeX:\n\n```latex\n'+s.get('latex','')+'\n```']
    if s['table']:md += ['\n'+'\n'.join(' | '.join(r) for r in s['table'])]
    if s.get('detail'):md += ['\nAdditional evidence: '+'; '.join(' = '.join(r) for r in s['detail'])]
    if s.get('legend'):md += ['\nNotation legend:\n\n'+'\n\n'.join(s['legend'])]
    if s.get('task_data'):md += ['\nData and models used:\n\n'+s['task_data']]
    md += [s.get('result') or '',s.get('limit') or '',s['notes'],'\nSources: '+', '.join(s['sources'])]
(ROOT/'output/presentations/supervisor_presenter_notes.md').write_text('\n\n'.join(md),encoding='utf-8')
print(f'Prepared {len(slides)} slides with all eleven original tasks and dataset provenance')
